name: sdfinal
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter_native_splash: ^2.3.4
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  google_mlkit_object_detection: ^0.11.0
  image_picker: ^1.0.1
  camera: ^0.10.5+2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_native_splash:
  color: "#04064D"
  image: assets/SafeDriveLogo.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/FindingVIN.jpg
    - assets/SafeDriveLogo.png
    - assets/UserProfile.png
    - assets/SDBackground.png
    - assets/FindingInsurance.png
    - assets/CallEMS.png
    - assets/DocumentationStep.png
    - assets/MultipleCars.png
    - assets/WhenPoliceArrive.png
    - assets/ExchangeInfo.png
    - assets/RestRecover.png
    - assets/custom_weights_final_tf.tflite
